# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# Or here for 3.4:
# https://symfony.com/doc/3.4/reference/configuration/security.html
security:

    acl:
        connection: default

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_db_provider:
            entity:
                class: AppBundle:User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate§

            provider: user_db_provider

            form_login:
                login_path: login # This value can also be route name
                check_path: login # This value can also be route name
                csrf_token_generator: security.csrf.token_manager

                username_parameter: _email
                password_parameter: _password

                always_use_default_target_path: true
                default_target_path: /

            logout:
                path: /logout # logout path, route name probably tii
                # success_handler: my_auth_handler

    role_hierarchy:
        ROLE_USER: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/photo/create, roles: ROLE_USER }
        - { path: ^/photo, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }




