<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * PhotoRepository
 *
 * More about query builder
 * http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWhereFriend(User $user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $confirmedUserIds = $user->getConfirmedFriendsIds();

        $results = $qb->select('p')
            ->from('AppBundle:Photo', 'p')
            ->where(
                $qb->expr()->in(
                    'p.creator', '?1'
                )
            )
            ->setParameter('1', $confirmedUserIds)
            ->getQuery()
            ->getResult();

        return $results;
    }
}
