<?php

namespace AppBundle\Repository;

/**
 * UserFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFriendRepository extends \Doctrine\ORM\EntityRepository
{
}
