<?php

namespace AppBundle\Repository;

/**
 * UserGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
