<?php

namespace AppBundle\Repository;

/**
 * UserGradePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGradePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
