<?php

namespace AppBundle\Repository;

/**
 * UserTagPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTagPhotoRepository extends \Doctrine\ORM\EntityRepository
{

}
