<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Photo;
use AppBundle\Entity\User;

/**
 * UserGradePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGradePhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByPhotoAndUser(Photo $photo, User $user)
    {
        return $this->findOneBy(['photo' => $photo, 'user' => $user]);
    }

}
