<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserTagPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTagPhotoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllTagsByUsers($userIds)
    {
        // More on query builder: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('t.name')
            ->from('AppBundle:UserTagPhoto', 'utp')
            ->leftJoin('utp.tag', 't')
            ->andWhere('utp.user IN (:ids)')
            ->setParameter('ids', $userIds);

        $result = $qb->getQuery()->getResult();

        $tags = [];
        foreach ($result as $userTagPhoto) {
            $tags[] = $userTagPhoto['name'];
        }

        $tagOccurences = array_count_values($tags);

        arsort($tagOccurences);

        return $tagOccurences;
    }
}
